apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gruck-test
  name: gruck-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gruck-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gruck-test
    spec:
      containers:
      - image: docker.io/adverity/task/gruck:latest
        name: gruck
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gruck-test
  name: gruck-test
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gruck-test
  type: ClusterIP
status:
  loadBalancer: {}
